const mongoose = require('mongoose');

const analyticsSchema = new mongoose.Schema(
    {
        user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User', // The user who asked the question
            required: true,
        },
        searchQuery: {
            type: String,
            required: [true, 'Search query cannot be empty'],
        },
        aiResponse: {
            type: String,
            required: true, // The answer generated by the AI
        },
        documentsUsed: [
            {
                type: mongoose.Schema.Types.ObjectId,
                ref: 'Document', // Which documents the AI used to generate the answer
            }
        ]
    },
    {
        timestamps: true,
    }
);

module.exports = mongoose.model('Analytics', analyticsSchema);